### ISSUE TITLE
Build rosetta-helium image from scratch

### ISSUE THREAD

**Issue by GeekArthur** [helium/rosetta-helium#38]
Currently the rosetta-helium image still uses blockchain-node image as runner image.

For example, in the mainnet Dockerfile: https://github.com/helium/rosetta-helium/blob/main/Dockerfile#L2, it uses `blockchain-node:blockchain-node-ubuntu18-1.1.47` from `quay.io`.

We need to build the rosetta-helium image from scratch for both mainnet and testnet for security reasons.

**Comment by evanmcc** [comment]
I think that we can make this configurable.

I don't know that it will be possible to fully sync the testnet, but I will test this.

**Comment by abhay** [comment]
@GeekArthur it should be possible to pass a BUILD_ARG into the docker build with other base images that contain the [blockchain-node](https://github.com/helium/blockchain-node) dependency.

**Comment by GeekArthur** [comment]
@evanmcc Thanks for testing the testnet and mainnet, please let me know once you have the result.

@abhay It's feasible but I think we still need to do security clearance for the base images that contain the blockchian-node dependency. I believe currently only the basic ubuntu image is trusted, and the whole building process will be in the Rosetta implementation on top the basic ubuntu image. We may clone the blockchain-node repo then trigger the building process with the corresponding dependencies, similar idea to [Ethereum](https://github.com/coinbase/rosetta-ethereum/blob/master/Dockerfile#L40) or [Cardano](https://github.com/input-output-hk/cardano-rosetta/blob/master/Dockerfile#L53)

**Comment by syuan100** [comment]
I'll add this to the bump_snap branch in a moment.
