### ISSUE TITLE
Add new txn support

### ISSUE THREAD

**Issue by syuan100** [helium/rosetta-helium#41]
- `update_gateway_oui_v1`: Fee only op
- `transfer_hotspot_v2`: Fee only op (simpler than v1)

**Comment by madninja** [comment]
Note that transfer-hotspot-v2 will be fixed to have the new owner pay the fees

**Comment by syuan100** [comment]
update_gateway_oui_v1 will require a blockchain-node change. Since there is no `gateway_owner` field in the pb, we will need to store it separately during absorb.
